language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-icecream' ]; then cd .. && eval "mv $currentfolder generator-icecream" && cd generator-icecream; fi
